In [45]:
# KNN Classifier

In [46]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [48]:
X=val[["mass", "width", "height"]]
y=val["fruit_label"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

d=dict(zip(val["fruit_label"].unique(), val["fruit_name"].unique()))
print(d)

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}


In [49]:
from sklearn.neighbors import KNeighborsClassifier
temp=KNeighborsClassifier(n_neighbors=5)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(d[temp.predict([[86, 5.9, 4.5]])[0]])

0.7954545454545454
0.5333333333333333
mandarin


In [50]:
# KNN Regressor

In [51]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [53]:
X=val[["width", "height", "color_score"]]
y=val["mass"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.neighbors import KNeighborsRegressor
temp=KNeighborsRegressor(n_neighbors=3)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(temp.predict([[6.1, 4.5, 0.78]]))

0.9338836200456677
0.8454773515731105
[82.]


In [54]:
#Linear Regression

In [55]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [57]:
X=val[["width", "height", "color_score"]]
y=val["mass"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_scaled_train=scaler.fit_transform(X_train)
X_scaled_test=scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
temp=LinearRegression()
temp.fit(X_scaled_train, y_train)
print(temp.score(X_scaled_train, y_train))
print(temp.score(X_scaled_test, y_test))
print(temp.coef_)
print(temp.intercept_)

0.852792608280449
0.8437315172347367
[163.10935946  87.64501329  21.22760748]
38.510211355088316


In [58]:
# Ridge

In [59]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [60]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [61]:
X=val[["width", "height", "color_score"]]
y=val["mass"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import Ridge
temp=Ridge(alpha=3)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(temp.coef_)
print(temp.intercept_)
print(temp.predict([[6.1, 4.5, 0.78]]))

0.842758695430618
0.8287947346489445
[43.52173601 13.23870538  3.96679104]
-251.44245650359338
[76.70840438]


In [62]:
#Lasso 

In [63]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [65]:
X=val[["width", "height", "color_score"]]
y=val["mass"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import Lasso
temp=Lasso(alpha=2)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(temp.coef_)
print(temp.intercept_)
print(temp.predict([[6.1, 4.5, 0.78]]))

0.8444487989729419
0.8358672054605487
[45.5270501  12.16708661  0.        ]
-254.35269643094787
[78.11419893]


In [66]:
# Logistic Regression

In [67]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [69]:
X=val[["mass", "width", "height"]]
y=val["fruit_label"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_scaled_train=scaler.fit_transform(X_train)
X_scaled_test=scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
temp=LogisticRegression(C=11)
temp.fit(X_scaled_train, y_train)
print(temp.score(X_scaled_train, y_train))
print(temp.score(X_scaled_test, y_test))
print(temp.coef_)
print(temp.intercept_)
print(d[temp.predict([[86, 5.9, 4.5]])[0]])

0.7727272727272727
0.5333333333333333
[[-3.36603187  6.2956769  -2.32629868]
 [-2.54546269 -2.5939934  -5.84094606]
 [ 3.48398273  1.27148075 -0.88873556]
 [-1.54541287 -6.61976389  7.12787242]]
[-0.81928956  1.32129698 -2.18155695 -2.28769495]
orange


C:\Users\Saurav\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
C:\Users\Saurav\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Saurav\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [70]:
# SVM 

In [71]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [72]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [73]:
X=val[["mass", "width", "height"]]
y=val["fruit_label"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

d=dict(zip(val["fruit_label"].unique(), val["fruit_name"].unique()))
print(d)

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}


In [74]:
from sklearn.svm import SVC
temp=SVC(C=3, kernel="rbf", gamma=0.01)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(d[temp.predict([[86, 5.9, 4.5]])[0]])

0.7954545454545454
0.5333333333333333
mandarin


In [75]:
# Decision Trees

In [76]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [77]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [78]:
X=val[["mass", "width", "height"]]
y=val["fruit_label"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

d=dict(zip(val["fruit_label"].unique(), val["fruit_name"].unique()))
print(d)

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}


In [79]:
from sklearn.tree import DecisionTreeClassifier
temp=DecisionTreeClassifier(max_depth=4)
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))
print(d[temp.predict([[86, 5.9, 4.5]])[0]])

0.9318181818181818
0.7333333333333333
mandarin


In [80]:
# Checking Cross Validation Score

In [81]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [82]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [83]:
X=val[["mass", "width", "height"]]
y=val["fruit_label"]

from sklearn.model_selection import cross_val_score

from sklearn.tree import DecisionTreeClassifier
temp=DecisionTreeClassifier(max_depth=4)

c=cross_val_score(temp, X, y, cv=5)
print(c)
print(np.mean(c))

[0.30769231 0.75       0.66666667 0.83333333 0.8       ]
0.6715384615384616


In [84]:
# Polynomial Regression

In [1]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
val=pd.read_csv("fruit_data_with_colors.txt", delimiter='\t')
val.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [6]:
X=val[["width", "height", "color_score"]]
y=val["mass"]
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3)
X_scaled=poly.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, random_state=0)
from sklearn.linear_model import LinearRegression
temp=LinearRegression()
temp.fit(X_train, y_train)
print(temp.score(X_train, y_train))
print(temp.score(X_test, y_test))

0.980749455209081
0.8477627760571413
