In [1]:
# Introduction to Python #

In [2]:
#Python has int, float, string but nothing like Character

a=12
b=34.56
c="Hello World!" 
print(a)
print(b)
print(c)
print("Hello!",end=" ")
print(34)
print(type(a))
print(type(b))
print(type(c))
print(type("Hello"))
print(type(34))
print(type('c'))

12
34.56
Hello World!
Hello! 34
<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'str'>


In [3]:
#   +, -, *, /(Actual Division), %, //(Quotient), **(To the power)

In [4]:
print(2+56.45)
print(9**3)
print(8/3)
print(8//3)
print(8%3)

58.45
729
2.6666666666666665
2
2


In [5]:
#By default python takes string as input

In [6]:
val=input()
print(val)

Hello
Hello


In [7]:
val1=int(input("Give an integer:"))
print(val1)

Give an integer:123
123


In [8]:
# if, elif, else 

In [9]:
a=int(input("Give a:"))
b=float(input("Give b:"))
if a>b:
    print("a is greater than b")
    print(a)
elif a==b:
    print("They are equal")
else:
    print("a is smaller than b")
    print(b)

Give a:45
Give b:34.55667
a is greater than b
45


In [10]:
# List

In [11]:
a=[12, 45.45, 78, [12, 61, "Saurav"], "Haha"]
print(a)

[12, 45.45, 78, [12, 61, 'Saurav'], 'Haha']


In [12]:
a.append("Hello!")
print(a)

[12, 45.45, 78, [12, 61, 'Saurav'], 'Haha', 'Hello!']


In [13]:
a.pop()
print(a)

[12, 45.45, 78, [12, 61, 'Saurav'], 'Haha']


In [14]:
print(a[0])

12


In [15]:
print(a[3])

[12, 61, 'Saurav']


In [16]:
print(a[3][2])

Saurav


In [17]:
print(a[-1])

Haha


In [18]:
print(a[-2][-3])

12


In [19]:
print(a[-2][0])

12


In [20]:
print(a)

[12, 45.45, 78, [12, 61, 'Saurav'], 'Haha']


In [21]:
print(a[1:4])

[45.45, 78, [12, 61, 'Saurav']]


In [22]:
print(a[:3])

[12, 45.45, 78]


In [23]:
print(a[3:])

[[12, 61, 'Saurav'], 'Haha']


In [24]:
b=[34, 76.56, 34, 87.12, 89, 10, -0.22]
print(b)
print(len(b))
print(max(b))
print(min(b))
print(sum(b))
b.sort()
print(b)
b.reverse()
print(b)

[34, 76.56, 34, 87.12, 89, 10, -0.22]
7
89
-0.22
330.46
[-0.22, 10, 34, 34, 76.56, 87.12, 89]
[89, 87.12, 76.56, 34, 34, 10, -0.22]


In [25]:
print(b[3:5])

[34, 34]


In [26]:
print(b[-4:-1])

[34, 34, 10]


In [27]:
print(list(range(6)))

[0, 1, 2, 3, 4, 5]


In [28]:
print(list(range(5, 14)))

[5, 6, 7, 8, 9, 10, 11, 12, 13]


In [29]:
print(list(range(3, 20, 2)))

[3, 5, 7, 9, 11, 13, 15, 17, 19]


In [30]:
#Looping

In [31]:
print(b)

[89, 87.12, 76.56, 34, 34, 10, -0.22]


In [32]:
sum1=0
for item in b:
    sum1=sum1+item
print(sum1)

330.46


In [33]:
print(sum(b))

330.46


In [34]:
sum1=0
i=0
while i<len(b):
    sum1=sum1+b[i]
    i=i+1
print(sum1)    

330.46


In [35]:
# Tuples       #We can't modify tuples once created

In [36]:
a=(12, 45.34, [56, 51], "Saurav")
print(a)

(12, 45.34, [56, 51], 'Saurav')


In [37]:
print(a[2])

[56, 51]


In [38]:
print(a[2][0])

56


In [41]:
b=(23, )
print(b)

(23,)


In [42]:
print(type(b))

<class 'tuple'>


In [43]:
#Sets  #Sets are not iteratable

In [44]:
a={12, 45, 12, 45, 12, 67, 89}
print(a)

{89, 67, 12, 45}


In [57]:
#Dictionary  #Keys are unique

In [58]:
d={"USA":23, "India":34, "Japan":19}
print(d)

{'USA': 23, 'India': 34, 'Japan': 19}


In [59]:
print(list(d.keys()))
print(list(d.values()))

['USA', 'India', 'Japan']
[23, 34, 19]


In [60]:
print(d["India"])

34


In [61]:
d["China"]=333
print(d)

{'USA': 23, 'India': 34, 'Japan': 19, 'China': 333}


In [62]:
d[100]=200
print(d)

{'USA': 23, 'India': 34, 'Japan': 19, 'China': 333, 100: 200}


In [63]:
del(d["Japan"])
print(d)

{'USA': 23, 'India': 34, 'China': 333, 100: 200}


In [64]:
del(d[100])
print(d)

{'USA': 23, 'India': 34, 'China': 333}


In [65]:
z={12:[34, 56, 78], 67:[67, 45], "Saurav":"Kumar"}
print(z)
print(z[12][2])

{12: [34, 56, 78], 67: [67, 45], 'Saurav': 'Kumar'}
78


In [66]:
#List Comp.

In [67]:
a=[12, 56, 78, 89, -10]
b=[item**2 for item in a]
print(b)

[144, 3136, 6084, 7921, 100]


In [68]:
c=[x for x in b if x%2==0 and x%3==0]
print(c)

[144, 6084]


In [69]:
#Functions

In [70]:
def fun():
    print("Hello!")
    
fun()    

Hello!


In [71]:
def fun_c(a, b):
    return(a+b)
val=fun_c(12, 5.34)
print(val)

17.34


In [72]:
#Lambdas :    They are ann. functions

In [73]:
val=lambda a, b, c : a+b+c
c=val(12, 1, 2)
print(c)

15


In [74]:
import collections
a=[12, 56, 12, 78, 12, 56, 78, 89, 100]
ctr=collections.Counter(a)
print(ctr)
val=ctr.most_common()
print(val)

Counter({12: 3, 56: 2, 78: 2, 89: 1, 100: 1})
[(12, 3), (56, 2), (78, 2), (89, 1), (100, 1)]


In [77]:
a=[[12, "A"], [0, "S"], [4, "B"]]
a.sort()
print(a)

[[0, 'S'], [4, 'B'], [12, 'A']]


In [78]:
b=[["X", 34], ["A", 51], ["C", 67]]
b.sort()
print(b)

[['A', 51], ['C', 67], ['X', 34]]


In [79]:
#map

In [80]:
a=[12, 45, 71, 89, 0]
def fun(val):
    return(val/2)

print(list(map(fun, a)))

[6.0, 22.5, 35.5, 44.5, 0.0]


In [133]:
#datetime in Python

In [141]:
import datetime as dt
a=dt.date(1999, 7, 10)
print(a)
print(a.year)
b=dt.time(3, 56, 56, 900)
print(b)
print(b.microsecond)
d=dt.timedelta(days=-100)
v=a+d
print(v)
c=dt.datetime(1999, 7, 10, 3, 34, 56, 899)
print(c)
print(c+d)

1999-07-10
1999
03:56:56.000900
900
1999-04-01
1999-07-10 03:34:56.000899
1999-04-01 03:34:56.000899


In [142]:
a="Saurav Kumar Nishant"
val="mar" in a
if val==True:
    print("Matched")
else:
    print("Not Matched")

Matched


In [143]:
b=a.split("a")
print(b)

['S', 'ur', 'v Kum', 'r Nish', 'nt']


In [81]:
# numpy in pythons #

In [82]:
import numpy as np

In [113]:
a=np.array([12, 67, 78, 56, 89])       #1-D array
print(a)
print(np.max(a))
print(np.argmax(a))
print(np.sum(a))
print(np.mean(a))
print(np.std(a))

[12 67 78 56 89]
89
4
302
60.4
26.58270114190806


In [114]:
print(a.size)

5


In [117]:
print(a[3])
print(a[1:4])

56
[67 78 56]


In [102]:
b=np.array([(12, 56, 78), (67, 89, 100)])       #2-D array
print(b)
print(np.max(b))
print(np.sum(b))

[[ 12  56  78]
 [ 67  89 100]]
100
402


In [103]:
print(b.shape)       #r*c
print(b.size)        #total number of elements

(2, 3)
6


In [104]:
z=b.reshape(3, 2)
print(z)

[[ 12  56]
 [ 78  67]
 [ 89 100]]


In [105]:
x=np.arange(6)
print(x)

[0 1 2 3 4 5]


In [106]:
c=x.reshape(2, 3)
print(c)

[[0 1 2]
 [3 4 5]]


In [107]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [108]:
w=np.ones((2, 5))
print(w)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [109]:
n=np.zeros((2, 4))
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [110]:
m=np.linspace(2, 7, 4)
print(m)

[2.         3.66666667 5.33333333 7.        ]


In [119]:
a=np.array([(12, 45, 67, 89, 56), (34, 5667, 4, 78, 1), (12, 78, 90, 56, 12), (31, 61, 81, 91, 1)])
print(a)
print(a.shape)

[[  12   45   67   89   56]
 [  34 5667    4   78    1]
 [  12   78   90   56   12]
 [  31   61   81   91    1]]
(4, 5)


In [120]:
print(a[2, 4])

12


In [121]:
print(a[1: , :2])

[[  34 5667]
 [  12   78]
 [  31   61]]


In [122]:
print(a[:, :1])

[[12]
 [34]
 [12]
 [31]]


In [124]:
a=np.array([(12, 45),(16, 7)])
b=np.array([(3, 7), [9, 90]])
print(a)
print()
print(b)

[[12 45]
 [16  7]]

[[ 3  7]
 [ 9 90]]


In [125]:
#element wise addition, substraction, multiplication, division, power

In [126]:
c=a+b
print(c)

[[15 52]
 [25 97]]


In [127]:
v=a*b
print(v)

[[ 36 315]
 [144 630]]


In [128]:
val=a.dot(b)
print(val)

[[ 441 4134]
 [ 111  742]]


In [131]:
a=np.array([(1, ), (2, ), (8, )])
print(a)
print()
print(a.T)

[[1]
 [2]
 [8]]

[[1 2 8]]


In [132]:
print(a.dot(a.T))

[[ 1  2  8]
 [ 2  4 16]
 [ 8 16 64]]
